#! /bin/sh
# Print colorschemes that should be removed

# First, go to the right directory...
dirok() { test -d colors ; }
for i in 1 2 3 4 5 6 7 8 ; do
        dirok || cd .. || exit
done
dirok || { echo>&2 botched directory; exit 123; }

exception() {
        for e in felipec.vim ; do
                test colors/"$e" = "$1" && return 0
        done
        false
}
grep -l current_syntax colors/*.vim | while read colo
do
        exception "$colo" || echo "$colo" || exit
done
